### PR TITLE
Updated ESLint version & rules, then fix code across project, and fixed #212

### LINKED ISSUE #212: Grid should also work properly with URL as set from `react-router`
**Do you want to request a *feature* or report a *bug* (建议还是bug) ?**
Request a feature. But it can be regarded as a bug too.

**What is the current behavior? (现有状况)**
Grid when click will take you to the target URL if you set `href`. But for the case if such target URL is as part of `react-router`'s URL, then it won't work when you build react into production build. It returns 404.

**What is the expected behavior? （应有状况）**
It should work the same even such URL is as part of `react-router`.

**Which versions of React-weui, weui, and which OS and device are affected by this issue? (React-weui版本 weui版本 机型和系统)**
React-weui: `1.0.3`
weui: `1.1.0`

### PR DESCRIPTION
**Pull request by haxpor**
Updated ESLint version. and its rules and fixed warnings/errors across project. Also with fixing of #212 

* already tested via `npm run test` and all tests passed.
* most of code fixed across the project are about semi colon, space
  after if/else if/else/for statement, removed newline at the end of file, a few dangerous code statement fixed, and a few that is not needed.
* ESlint is updated to version `3.17.1`. The project has used version
  `1.x.x`. This should be better.
* ESLint's rules are updated to be more stricted but not too strict. See
  it in .eslintrc.
* fixed #212 

## Fixed #212 
Tested, It works fine and can provide normal `<a>` functionality to link to normal URL, or `react-router`'s URL.

We can use the following code in `Grid`'s Data.

```javascript
const data = [
  {
    icon: <img src={issue_icon} alt="issue icon"/>,
    label: 'Issues ...',
    to: '/issues'
  },
  {
    icon: <img src={project_icon} alt="project icon"/>,
    label: 'Projects',
    to: '/projects'
  },
  {
    icon: <img src={contribute_icon} alt="contribute icon"/>,
    label: 'Contributes',
    href: 'https://google.com'
  }
];
```

The first two items are for `react-router`'s URL, and the third one is for normal URL. When click, it takes to destination properly.

Anyway, the code seems easy and straightforward but not sure it should be the approach use or not as it directly use `react-router`'s `<Link>` and I checked `react-weui` already depends on it although older version.

### CODE REVIEW

File: src/components/grid/grid.js [hunk 1]
```diff
@@ -2,6 +2,7 @@ import React from 'react';
 import classNames from 'classnames';
 import GridIcon from './grid_icon';
 import GridLabel from './grid_label';
+import { Link } from 'react-router';
```
Comment (n7best) [inline src/components/grid/grid.js]: @haxpor Thanks for the PR and work to the lint!

I believe to use Link in this case will require dependency from react-router and not everyone use react-router as router even though most of the single page application do. 

Can you modify it to something like [Cell](https://github.com/weui/react-weui/blob/master/src/components/cell/cell.js) that people will be able to pass into their component?

Comment (haxpor) [inline src/components/grid/grid.js]: Agree! That's much more robust.

I've fixed it to provide `component` property to be set in Grid as similar to `Cell` class.
